import React from "react";
import { ExperienceWrapper } from "./experienceElements";

const Experience = () => {
  return (
    <ExperienceWrapper id="experience">
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience experience experience
      experience experience experience experience
    </ExperienceWrapper>
  );
};

export default Experience;
